# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import SimpleGrpcServer_pb2 as SimpleGrpcServer__pb2


class SimpleGrpcServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Test1 = channel.unary_unary(
        '/pravega_simple_grpc_server.SimpleGrpcServer/Test1',
        request_serializer=SimpleGrpcServer__pb2.Test1Request.SerializeToString,
        response_deserializer=SimpleGrpcServer__pb2.Test1Reply.FromString,
        )
    self.Test2 = channel.unary_unary(
        '/pravega_simple_grpc_server.SimpleGrpcServer/Test2',
        request_serializer=SimpleGrpcServer__pb2.Test1Request.SerializeToString,
        response_deserializer=SimpleGrpcServer__pb2.Test1Reply.FromString,
        )


class SimpleGrpcServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Test1(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Test2(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimpleGrpcServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Test1': grpc.unary_unary_rpc_method_handler(
          servicer.Test1,
          request_deserializer=SimpleGrpcServer__pb2.Test1Request.FromString,
          response_serializer=SimpleGrpcServer__pb2.Test1Reply.SerializeToString,
      ),
      'Test2': grpc.unary_unary_rpc_method_handler(
          servicer.Test2,
          request_deserializer=SimpleGrpcServer__pb2.Test1Request.FromString,
          response_serializer=SimpleGrpcServer__pb2.Test1Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pravega_simple_grpc_server.SimpleGrpcServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
