# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimpleGrpcServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SimpleGrpcServer.proto',
  package='pravega_simple_grpc_server',
  syntax='proto3',
  serialized_options=_b('\n%io.pravega.example.simple_grpc_serverB\025SimpleGrpcServerProtoP\001\242\002\004PSGS'),
  serialized_pb=_b('\n\x16SimpleGrpcServer.proto\x12\x1apravega_simple_grpc_server\"\x1c\n\x0cTest1Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nTest1Reply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8a\x03\n\x10SimpleGrpcServer\x12[\n\x05Test1\x12(.pravega_simple_grpc_server.Test1Request\x1a&.pravega_simple_grpc_server.Test1Reply\"\x00\x12[\n\x05Test2\x12(.pravega_simple_grpc_server.Test1Request\x1a&.pravega_simple_grpc_server.Test1Reply\"\x00\x12]\n\x05Test3\x12(.pravega_simple_grpc_server.Test1Request\x1a&.pravega_simple_grpc_server.Test1Reply\"\x00\x30\x01\x12]\n\x05Test4\x12(.pravega_simple_grpc_server.Test1Request\x1a&.pravega_simple_grpc_server.Test1Reply\"\x00\x30\x01\x42G\n%io.pravega.example.simple_grpc_serverB\x15SimpleGrpcServerProtoP\x01\xa2\x02\x04PSGSb\x06proto3')
)




_TEST1REQUEST = _descriptor.Descriptor(
  name='Test1Request',
  full_name='pravega_simple_grpc_server.Test1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pravega_simple_grpc_server.Test1Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=82,
)


_TEST1REPLY = _descriptor.Descriptor(
  name='Test1Reply',
  full_name='pravega_simple_grpc_server.Test1Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pravega_simple_grpc_server.Test1Reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['Test1Request'] = _TEST1REQUEST
DESCRIPTOR.message_types_by_name['Test1Reply'] = _TEST1REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Test1Request = _reflection.GeneratedProtocolMessageType('Test1Request', (_message.Message,), dict(
  DESCRIPTOR = _TEST1REQUEST,
  __module__ = 'SimpleGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:pravega_simple_grpc_server.Test1Request)
  ))
_sym_db.RegisterMessage(Test1Request)

Test1Reply = _reflection.GeneratedProtocolMessageType('Test1Reply', (_message.Message,), dict(
  DESCRIPTOR = _TEST1REPLY,
  __module__ = 'SimpleGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:pravega_simple_grpc_server.Test1Reply)
  ))
_sym_db.RegisterMessage(Test1Reply)


DESCRIPTOR._options = None

_SIMPLEGRPCSERVER = _descriptor.ServiceDescriptor(
  name='SimpleGrpcServer',
  full_name='pravega_simple_grpc_server.SimpleGrpcServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=116,
  serialized_end=510,
  methods=[
  _descriptor.MethodDescriptor(
    name='Test1',
    full_name='pravega_simple_grpc_server.SimpleGrpcServer.Test1',
    index=0,
    containing_service=None,
    input_type=_TEST1REQUEST,
    output_type=_TEST1REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Test2',
    full_name='pravega_simple_grpc_server.SimpleGrpcServer.Test2',
    index=1,
    containing_service=None,
    input_type=_TEST1REQUEST,
    output_type=_TEST1REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Test3',
    full_name='pravega_simple_grpc_server.SimpleGrpcServer.Test3',
    index=2,
    containing_service=None,
    input_type=_TEST1REQUEST,
    output_type=_TEST1REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Test4',
    full_name='pravega_simple_grpc_server.SimpleGrpcServer.Test4',
    index=3,
    containing_service=None,
    input_type=_TEST1REQUEST,
    output_type=_TEST1REPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLEGRPCSERVER)

DESCRIPTOR.services_by_name['SimpleGrpcServer'] = _SIMPLEGRPCSERVER

# @@protoc_insertion_point(module_scope)
